// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: install-service.proto

#include "install-service.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace agent {
namespace DTO {
PROTOBUF_CONSTEXPR InstallServiceInfo::InstallServiceInfo(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.install_service_request_id_)*/nullptr
  , /*decltype(_impl_.agent_id_)*/nullptr
  , /*decltype(_impl_.service_version_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct InstallServiceInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InstallServiceInfoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~InstallServiceInfoDefaultTypeInternal() {}
  union {
    InstallServiceInfo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InstallServiceInfoDefaultTypeInternal _InstallServiceInfo_default_instance_;
PROTOBUF_CONSTEXPR InstallServiceResult::InstallServiceResult(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.error_)*/nullptr
  , /*decltype(_impl_.status_)*/ 0

  , /*decltype(_impl_._cached_size_)*/{}} {}
struct InstallServiceResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InstallServiceResultDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~InstallServiceResultDefaultTypeInternal() {}
  union {
    InstallServiceResult _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InstallServiceResultDefaultTypeInternal _InstallServiceResult_default_instance_;
}  // namespace DTO
}  // namespace agent
static ::_pb::Metadata file_level_metadata_install_2dservice_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_install_2dservice_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_install_2dservice_2eproto = nullptr;
const ::uint32_t TableStruct_install_2dservice_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::agent::DTO::InstallServiceInfo, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::agent::DTO::InstallServiceInfo, _impl_.install_service_request_id_),
    PROTOBUF_FIELD_OFFSET(::agent::DTO::InstallServiceInfo, _impl_.agent_id_),
    PROTOBUF_FIELD_OFFSET(::agent::DTO::InstallServiceInfo, _impl_.service_version_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::agent::DTO::InstallServiceResult, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::agent::DTO::InstallServiceResult, _impl_.status_),
    PROTOBUF_FIELD_OFFSET(::agent::DTO::InstallServiceResult, _impl_.error_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, -1, -1, sizeof(::agent::DTO::InstallServiceInfo)},
        { 11, -1, -1, sizeof(::agent::DTO::InstallServiceResult)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::agent::DTO::_InstallServiceInfo_default_instance_._instance,
    &::agent::DTO::_InstallServiceResult_default_instance_._instance,
};
const char descriptor_table_protodef_install_2dservice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\025install-service.proto\022\tagent.DTO\032\014comm"
    "on.proto\"\227\001\n\022InstallServiceInfo\0220\n\032insta"
    "ll_service_request_id\030\001 \001(\0132\014.common.UUI"
    "D\022\036\n\010agent_id\030\002 \001(\0132\014.common.UUID\022/\n\017ser"
    "vice_version\030\003 \001(\0132\026.common.ServiceVersi"
    "on\"T\n\024InstallServiceResult\022\036\n\006status\030\001 \001"
    "(\0162\016.common.Status\022\034\n\005error\030\002 \001(\0132\r.comm"
    "on.Errorb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_install_2dservice_2eproto_deps[1] =
    {
        &::descriptor_table_common_2eproto,
};
static ::absl::once_flag descriptor_table_install_2dservice_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_install_2dservice_2eproto = {
    false,
    false,
    296,
    descriptor_table_protodef_install_2dservice_2eproto,
    "install-service.proto",
    &descriptor_table_install_2dservice_2eproto_once,
    descriptor_table_install_2dservice_2eproto_deps,
    1,
    2,
    schemas,
    file_default_instances,
    TableStruct_install_2dservice_2eproto::offsets,
    file_level_metadata_install_2dservice_2eproto,
    file_level_enum_descriptors_install_2dservice_2eproto,
    file_level_service_descriptors_install_2dservice_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_install_2dservice_2eproto_getter() {
  return &descriptor_table_install_2dservice_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_install_2dservice_2eproto(&descriptor_table_install_2dservice_2eproto);
namespace agent {
namespace DTO {
// ===================================================================

class InstallServiceInfo::_Internal {
 public:
  static const ::common::UUID& install_service_request_id(const InstallServiceInfo* msg);
  static const ::common::UUID& agent_id(const InstallServiceInfo* msg);
  static const ::common::ServiceVersion& service_version(const InstallServiceInfo* msg);
};

const ::common::UUID&
InstallServiceInfo::_Internal::install_service_request_id(const InstallServiceInfo* msg) {
  return *msg->_impl_.install_service_request_id_;
}
const ::common::UUID&
InstallServiceInfo::_Internal::agent_id(const InstallServiceInfo* msg) {
  return *msg->_impl_.agent_id_;
}
const ::common::ServiceVersion&
InstallServiceInfo::_Internal::service_version(const InstallServiceInfo* msg) {
  return *msg->_impl_.service_version_;
}
void InstallServiceInfo::clear_install_service_request_id() {
  if (GetArenaForAllocation() == nullptr && _impl_.install_service_request_id_ != nullptr) {
    delete _impl_.install_service_request_id_;
  }
  _impl_.install_service_request_id_ = nullptr;
}
void InstallServiceInfo::clear_agent_id() {
  if (GetArenaForAllocation() == nullptr && _impl_.agent_id_ != nullptr) {
    delete _impl_.agent_id_;
  }
  _impl_.agent_id_ = nullptr;
}
void InstallServiceInfo::clear_service_version() {
  if (GetArenaForAllocation() == nullptr && _impl_.service_version_ != nullptr) {
    delete _impl_.service_version_;
  }
  _impl_.service_version_ = nullptr;
}
InstallServiceInfo::InstallServiceInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:agent.DTO.InstallServiceInfo)
}
InstallServiceInfo::InstallServiceInfo(const InstallServiceInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  InstallServiceInfo* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.install_service_request_id_){nullptr}
    , decltype(_impl_.agent_id_){nullptr}
    , decltype(_impl_.service_version_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_install_service_request_id()) {
    _this->_impl_.install_service_request_id_ = new ::common::UUID(*from._impl_.install_service_request_id_);
  }
  if (from._internal_has_agent_id()) {
    _this->_impl_.agent_id_ = new ::common::UUID(*from._impl_.agent_id_);
  }
  if (from._internal_has_service_version()) {
    _this->_impl_.service_version_ = new ::common::ServiceVersion(*from._impl_.service_version_);
  }
  // @@protoc_insertion_point(copy_constructor:agent.DTO.InstallServiceInfo)
}

inline void InstallServiceInfo::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.install_service_request_id_){nullptr}
    , decltype(_impl_.agent_id_){nullptr}
    , decltype(_impl_.service_version_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

InstallServiceInfo::~InstallServiceInfo() {
  // @@protoc_insertion_point(destructor:agent.DTO.InstallServiceInfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void InstallServiceInfo::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.install_service_request_id_;
  if (this != internal_default_instance()) delete _impl_.agent_id_;
  if (this != internal_default_instance()) delete _impl_.service_version_;
}

void InstallServiceInfo::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void InstallServiceInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:agent.DTO.InstallServiceInfo)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.install_service_request_id_ != nullptr) {
    delete _impl_.install_service_request_id_;
  }
  _impl_.install_service_request_id_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.agent_id_ != nullptr) {
    delete _impl_.agent_id_;
  }
  _impl_.agent_id_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.service_version_ != nullptr) {
    delete _impl_.service_version_;
  }
  _impl_.service_version_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* InstallServiceInfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .common.UUID install_service_request_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_install_service_request_id(), ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // .common.UUID agent_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_agent_id(), ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // .common.ServiceVersion service_version = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_service_version(), ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* InstallServiceInfo::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:agent.DTO.InstallServiceInfo)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .common.UUID install_service_request_id = 1;
  if (this->_internal_has_install_service_request_id()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::install_service_request_id(this),
        _Internal::install_service_request_id(this).GetCachedSize(), target, stream);
  }

  // .common.UUID agent_id = 2;
  if (this->_internal_has_agent_id()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::agent_id(this),
        _Internal::agent_id(this).GetCachedSize(), target, stream);
  }

  // .common.ServiceVersion service_version = 3;
  if (this->_internal_has_service_version()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::service_version(this),
        _Internal::service_version(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:agent.DTO.InstallServiceInfo)
  return target;
}

::size_t InstallServiceInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:agent.DTO.InstallServiceInfo)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .common.UUID install_service_request_id = 1;
  if (this->_internal_has_install_service_request_id()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.install_service_request_id_);
  }

  // .common.UUID agent_id = 2;
  if (this->_internal_has_agent_id()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.agent_id_);
  }

  // .common.ServiceVersion service_version = 3;
  if (this->_internal_has_service_version()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.service_version_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData InstallServiceInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    InstallServiceInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*InstallServiceInfo::GetClassData() const { return &_class_data_; }


void InstallServiceInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<InstallServiceInfo*>(&to_msg);
  auto& from = static_cast<const InstallServiceInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:agent.DTO.InstallServiceInfo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_install_service_request_id()) {
    _this->_internal_mutable_install_service_request_id()->::common::UUID::MergeFrom(
        from._internal_install_service_request_id());
  }
  if (from._internal_has_agent_id()) {
    _this->_internal_mutable_agent_id()->::common::UUID::MergeFrom(
        from._internal_agent_id());
  }
  if (from._internal_has_service_version()) {
    _this->_internal_mutable_service_version()->::common::ServiceVersion::MergeFrom(
        from._internal_service_version());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void InstallServiceInfo::CopyFrom(const InstallServiceInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:agent.DTO.InstallServiceInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InstallServiceInfo::IsInitialized() const {
  return true;
}

void InstallServiceInfo::InternalSwap(InstallServiceInfo* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(InstallServiceInfo, _impl_.service_version_)
      + sizeof(InstallServiceInfo::_impl_.service_version_)
      - PROTOBUF_FIELD_OFFSET(InstallServiceInfo, _impl_.install_service_request_id_)>(
          reinterpret_cast<char*>(&_impl_.install_service_request_id_),
          reinterpret_cast<char*>(&other->_impl_.install_service_request_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata InstallServiceInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_install_2dservice_2eproto_getter, &descriptor_table_install_2dservice_2eproto_once,
      file_level_metadata_install_2dservice_2eproto[0]);
}
// ===================================================================

class InstallServiceResult::_Internal {
 public:
  static const ::common::Error& error(const InstallServiceResult* msg);
};

const ::common::Error&
InstallServiceResult::_Internal::error(const InstallServiceResult* msg) {
  return *msg->_impl_.error_;
}
void InstallServiceResult::clear_error() {
  if (GetArenaForAllocation() == nullptr && _impl_.error_ != nullptr) {
    delete _impl_.error_;
  }
  _impl_.error_ = nullptr;
}
InstallServiceResult::InstallServiceResult(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:agent.DTO.InstallServiceResult)
}
InstallServiceResult::InstallServiceResult(const InstallServiceResult& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  InstallServiceResult* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.error_){nullptr}
    , decltype(_impl_.status_) {}

    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_error()) {
    _this->_impl_.error_ = new ::common::Error(*from._impl_.error_);
  }
  _this->_impl_.status_ = from._impl_.status_;
  // @@protoc_insertion_point(copy_constructor:agent.DTO.InstallServiceResult)
}

inline void InstallServiceResult::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.error_){nullptr}
    , decltype(_impl_.status_) { 0 }

    , /*decltype(_impl_._cached_size_)*/{}
  };
}

InstallServiceResult::~InstallServiceResult() {
  // @@protoc_insertion_point(destructor:agent.DTO.InstallServiceResult)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void InstallServiceResult::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.error_;
}

void InstallServiceResult::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void InstallServiceResult::Clear() {
// @@protoc_insertion_point(message_clear_start:agent.DTO.InstallServiceResult)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.error_ != nullptr) {
    delete _impl_.error_;
  }
  _impl_.error_ = nullptr;
  _impl_.status_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* InstallServiceResult::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .common.Status status = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 8)) {
          ::uint32_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
          _internal_set_status(static_cast<::common::Status>(val));
        } else {
          goto handle_unusual;
        }
        continue;
      // .common.Error error = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_error(), ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* InstallServiceResult::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:agent.DTO.InstallServiceResult)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .common.Status status = 1;
  if (this->_internal_status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_status(), target);
  }

  // .common.Error error = 2;
  if (this->_internal_has_error()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::error(this),
        _Internal::error(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:agent.DTO.InstallServiceResult)
  return target;
}

::size_t InstallServiceResult::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:agent.DTO.InstallServiceResult)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .common.Error error = 2;
  if (this->_internal_has_error()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.error_);
  }

  // .common.Status status = 1;
  if (this->_internal_status() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_status());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData InstallServiceResult::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    InstallServiceResult::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*InstallServiceResult::GetClassData() const { return &_class_data_; }


void InstallServiceResult::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<InstallServiceResult*>(&to_msg);
  auto& from = static_cast<const InstallServiceResult&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:agent.DTO.InstallServiceResult)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_error()) {
    _this->_internal_mutable_error()->::common::Error::MergeFrom(
        from._internal_error());
  }
  if (from._internal_status() != 0) {
    _this->_internal_set_status(from._internal_status());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void InstallServiceResult::CopyFrom(const InstallServiceResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:agent.DTO.InstallServiceResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InstallServiceResult::IsInitialized() const {
  return true;
}

void InstallServiceResult::InternalSwap(InstallServiceResult* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(InstallServiceResult, _impl_.status_)
      + sizeof(InstallServiceResult::_impl_.status_)
      - PROTOBUF_FIELD_OFFSET(InstallServiceResult, _impl_.error_)>(
          reinterpret_cast<char*>(&_impl_.error_),
          reinterpret_cast<char*>(&other->_impl_.error_));
}

::PROTOBUF_NAMESPACE_ID::Metadata InstallServiceResult::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_install_2dservice_2eproto_getter, &descriptor_table_install_2dservice_2eproto_once,
      file_level_metadata_install_2dservice_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace DTO
}  // namespace agent
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::agent::DTO::InstallServiceInfo*
Arena::CreateMaybeMessage< ::agent::DTO::InstallServiceInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::agent::DTO::InstallServiceInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::agent::DTO::InstallServiceResult*
Arena::CreateMaybeMessage< ::agent::DTO::InstallServiceResult >(Arena* arena) {
  return Arena::CreateMessageInternal< ::agent::DTO::InstallServiceResult >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
