// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: update-available-versions.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_update_2davailable_2dversions_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_update_2davailable_2dversions_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4022000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4022001 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "common.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_update_2davailable_2dversions_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_update_2davailable_2dversions_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_update_2davailable_2dversions_2eproto;
namespace agent {
namespace DTO {
class UpdateAvailableVersionsInfo;
struct UpdateAvailableVersionsInfoDefaultTypeInternal;
extern UpdateAvailableVersionsInfoDefaultTypeInternal _UpdateAvailableVersionsInfo_default_instance_;
class UpdateAvailableVersionsResult;
struct UpdateAvailableVersionsResultDefaultTypeInternal;
extern UpdateAvailableVersionsResultDefaultTypeInternal _UpdateAvailableVersionsResult_default_instance_;
class VersionMatrix;
struct VersionMatrixDefaultTypeInternal;
extern VersionMatrixDefaultTypeInternal _VersionMatrix_default_instance_;
}  // namespace DTO
}  // namespace agent
PROTOBUF_NAMESPACE_OPEN
template <>
::agent::DTO::UpdateAvailableVersionsInfo* Arena::CreateMaybeMessage<::agent::DTO::UpdateAvailableVersionsInfo>(Arena*);
template <>
::agent::DTO::UpdateAvailableVersionsResult* Arena::CreateMaybeMessage<::agent::DTO::UpdateAvailableVersionsResult>(Arena*);
template <>
::agent::DTO::VersionMatrix* Arena::CreateMaybeMessage<::agent::DTO::VersionMatrix>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace agent {
namespace DTO {

// ===================================================================


// -------------------------------------------------------------------

class VersionMatrix final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:agent.DTO.VersionMatrix) */ {
 public:
  inline VersionMatrix() : VersionMatrix(nullptr) {}
  ~VersionMatrix() override;
  explicit PROTOBUF_CONSTEXPR VersionMatrix(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  VersionMatrix(const VersionMatrix& from);
  VersionMatrix(VersionMatrix&& from) noexcept
    : VersionMatrix() {
    *this = ::std::move(from);
  }

  inline VersionMatrix& operator=(const VersionMatrix& from) {
    CopyFrom(from);
    return *this;
  }
  inline VersionMatrix& operator=(VersionMatrix&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VersionMatrix& default_instance() {
    return *internal_default_instance();
  }
  static inline const VersionMatrix* internal_default_instance() {
    return reinterpret_cast<const VersionMatrix*>(
               &_VersionMatrix_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(VersionMatrix& a, VersionMatrix& b) {
    a.Swap(&b);
  }
  inline void Swap(VersionMatrix* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VersionMatrix* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VersionMatrix* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<VersionMatrix>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const VersionMatrix& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const VersionMatrix& from) {
    VersionMatrix::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VersionMatrix* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "agent.DTO.VersionMatrix";
  }
  protected:
  explicit VersionMatrix(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kServiceVersionFieldNumber = 2,
    kAgentVersionFieldNumber = 1,
  };
  // repeated .common.ServiceVersion service_version = 2;
  int service_version_size() const;
  private:
  int _internal_service_version_size() const;

  public:
  void clear_service_version() ;
  ::common::ServiceVersion* mutable_service_version(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::common::ServiceVersion >*
      mutable_service_version();
  private:
  const ::common::ServiceVersion& _internal_service_version(int index) const;
  ::common::ServiceVersion* _internal_add_service_version();
  public:
  const ::common::ServiceVersion& service_version(int index) const;
  ::common::ServiceVersion* add_service_version();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::common::ServiceVersion >&
      service_version() const;
  // .common.AgentVersion agent_version = 1;
  bool has_agent_version() const;
  private:
  bool _internal_has_agent_version() const;

  public:
  void clear_agent_version() ;
  const ::common::AgentVersion& agent_version() const;
  PROTOBUF_NODISCARD ::common::AgentVersion* release_agent_version();
  ::common::AgentVersion* mutable_agent_version();
  void set_allocated_agent_version(::common::AgentVersion* agent_version);
  private:
  const ::common::AgentVersion& _internal_agent_version() const;
  ::common::AgentVersion* _internal_mutable_agent_version();
  public:
  void unsafe_arena_set_allocated_agent_version(
      ::common::AgentVersion* agent_version);
  ::common::AgentVersion* unsafe_arena_release_agent_version();
  // @@protoc_insertion_point(class_scope:agent.DTO.VersionMatrix)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::common::ServiceVersion > service_version_;
    ::common::AgentVersion* agent_version_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_update_2davailable_2dversions_2eproto;
};// -------------------------------------------------------------------

class UpdateAvailableVersionsInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:agent.DTO.UpdateAvailableVersionsInfo) */ {
 public:
  inline UpdateAvailableVersionsInfo() : UpdateAvailableVersionsInfo(nullptr) {}
  ~UpdateAvailableVersionsInfo() override;
  explicit PROTOBUF_CONSTEXPR UpdateAvailableVersionsInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UpdateAvailableVersionsInfo(const UpdateAvailableVersionsInfo& from);
  UpdateAvailableVersionsInfo(UpdateAvailableVersionsInfo&& from) noexcept
    : UpdateAvailableVersionsInfo() {
    *this = ::std::move(from);
  }

  inline UpdateAvailableVersionsInfo& operator=(const UpdateAvailableVersionsInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline UpdateAvailableVersionsInfo& operator=(UpdateAvailableVersionsInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UpdateAvailableVersionsInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const UpdateAvailableVersionsInfo* internal_default_instance() {
    return reinterpret_cast<const UpdateAvailableVersionsInfo*>(
               &_UpdateAvailableVersionsInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(UpdateAvailableVersionsInfo& a, UpdateAvailableVersionsInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(UpdateAvailableVersionsInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UpdateAvailableVersionsInfo* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UpdateAvailableVersionsInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UpdateAvailableVersionsInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UpdateAvailableVersionsInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const UpdateAvailableVersionsInfo& from) {
    UpdateAvailableVersionsInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UpdateAvailableVersionsInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "agent.DTO.UpdateAvailableVersionsInfo";
  }
  protected:
  explicit UpdateAvailableVersionsInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUpgradableVersionsFieldNumber = 5,
    kUpdateAvailableVersionsRequestIdFieldNumber = 1,
    kAgentIdFieldNumber = 2,
    kCurrentAgentVersionFieldNumber = 3,
    kCurrentServiceVersionFieldNumber = 4,
  };
  // repeated .agent.DTO.VersionMatrix upgradable_versions = 5;
  int upgradable_versions_size() const;
  private:
  int _internal_upgradable_versions_size() const;

  public:
  void clear_upgradable_versions() ;
  ::agent::DTO::VersionMatrix* mutable_upgradable_versions(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::agent::DTO::VersionMatrix >*
      mutable_upgradable_versions();
  private:
  const ::agent::DTO::VersionMatrix& _internal_upgradable_versions(int index) const;
  ::agent::DTO::VersionMatrix* _internal_add_upgradable_versions();
  public:
  const ::agent::DTO::VersionMatrix& upgradable_versions(int index) const;
  ::agent::DTO::VersionMatrix* add_upgradable_versions();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::agent::DTO::VersionMatrix >&
      upgradable_versions() const;
  // .common.UUID update_available_versions_request_id = 1;
  bool has_update_available_versions_request_id() const;
  private:
  bool _internal_has_update_available_versions_request_id() const;

  public:
  void clear_update_available_versions_request_id() ;
  const ::common::UUID& update_available_versions_request_id() const;
  PROTOBUF_NODISCARD ::common::UUID* release_update_available_versions_request_id();
  ::common::UUID* mutable_update_available_versions_request_id();
  void set_allocated_update_available_versions_request_id(::common::UUID* update_available_versions_request_id);
  private:
  const ::common::UUID& _internal_update_available_versions_request_id() const;
  ::common::UUID* _internal_mutable_update_available_versions_request_id();
  public:
  void unsafe_arena_set_allocated_update_available_versions_request_id(
      ::common::UUID* update_available_versions_request_id);
  ::common::UUID* unsafe_arena_release_update_available_versions_request_id();
  // .common.UUID agent_id = 2;
  bool has_agent_id() const;
  private:
  bool _internal_has_agent_id() const;

  public:
  void clear_agent_id() ;
  const ::common::UUID& agent_id() const;
  PROTOBUF_NODISCARD ::common::UUID* release_agent_id();
  ::common::UUID* mutable_agent_id();
  void set_allocated_agent_id(::common::UUID* agent_id);
  private:
  const ::common::UUID& _internal_agent_id() const;
  ::common::UUID* _internal_mutable_agent_id();
  public:
  void unsafe_arena_set_allocated_agent_id(
      ::common::UUID* agent_id);
  ::common::UUID* unsafe_arena_release_agent_id();
  // .common.AgentVersion current_agent_version = 3;
  bool has_current_agent_version() const;
  private:
  bool _internal_has_current_agent_version() const;

  public:
  void clear_current_agent_version() ;
  const ::common::AgentVersion& current_agent_version() const;
  PROTOBUF_NODISCARD ::common::AgentVersion* release_current_agent_version();
  ::common::AgentVersion* mutable_current_agent_version();
  void set_allocated_current_agent_version(::common::AgentVersion* current_agent_version);
  private:
  const ::common::AgentVersion& _internal_current_agent_version() const;
  ::common::AgentVersion* _internal_mutable_current_agent_version();
  public:
  void unsafe_arena_set_allocated_current_agent_version(
      ::common::AgentVersion* current_agent_version);
  ::common::AgentVersion* unsafe_arena_release_current_agent_version();
  // .common.ServiceVersion current_service_version = 4;
  bool has_current_service_version() const;
  private:
  bool _internal_has_current_service_version() const;

  public:
  void clear_current_service_version() ;
  const ::common::ServiceVersion& current_service_version() const;
  PROTOBUF_NODISCARD ::common::ServiceVersion* release_current_service_version();
  ::common::ServiceVersion* mutable_current_service_version();
  void set_allocated_current_service_version(::common::ServiceVersion* current_service_version);
  private:
  const ::common::ServiceVersion& _internal_current_service_version() const;
  ::common::ServiceVersion* _internal_mutable_current_service_version();
  public:
  void unsafe_arena_set_allocated_current_service_version(
      ::common::ServiceVersion* current_service_version);
  ::common::ServiceVersion* unsafe_arena_release_current_service_version();
  // @@protoc_insertion_point(class_scope:agent.DTO.UpdateAvailableVersionsInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::agent::DTO::VersionMatrix > upgradable_versions_;
    ::common::UUID* update_available_versions_request_id_;
    ::common::UUID* agent_id_;
    ::common::AgentVersion* current_agent_version_;
    ::common::ServiceVersion* current_service_version_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_update_2davailable_2dversions_2eproto;
};// -------------------------------------------------------------------

class UpdateAvailableVersionsResult final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:agent.DTO.UpdateAvailableVersionsResult) */ {
 public:
  inline UpdateAvailableVersionsResult() : UpdateAvailableVersionsResult(nullptr) {}
  ~UpdateAvailableVersionsResult() override;
  explicit PROTOBUF_CONSTEXPR UpdateAvailableVersionsResult(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UpdateAvailableVersionsResult(const UpdateAvailableVersionsResult& from);
  UpdateAvailableVersionsResult(UpdateAvailableVersionsResult&& from) noexcept
    : UpdateAvailableVersionsResult() {
    *this = ::std::move(from);
  }

  inline UpdateAvailableVersionsResult& operator=(const UpdateAvailableVersionsResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline UpdateAvailableVersionsResult& operator=(UpdateAvailableVersionsResult&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UpdateAvailableVersionsResult& default_instance() {
    return *internal_default_instance();
  }
  static inline const UpdateAvailableVersionsResult* internal_default_instance() {
    return reinterpret_cast<const UpdateAvailableVersionsResult*>(
               &_UpdateAvailableVersionsResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(UpdateAvailableVersionsResult& a, UpdateAvailableVersionsResult& b) {
    a.Swap(&b);
  }
  inline void Swap(UpdateAvailableVersionsResult* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UpdateAvailableVersionsResult* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UpdateAvailableVersionsResult* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UpdateAvailableVersionsResult>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UpdateAvailableVersionsResult& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const UpdateAvailableVersionsResult& from) {
    UpdateAvailableVersionsResult::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UpdateAvailableVersionsResult* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "agent.DTO.UpdateAvailableVersionsResult";
  }
  protected:
  explicit UpdateAvailableVersionsResult(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrorFieldNumber = 2,
    kStatusFieldNumber = 1,
  };
  // .common.Error error = 2;
  bool has_error() const;
  private:
  bool _internal_has_error() const;

  public:
  void clear_error() ;
  const ::common::Error& error() const;
  PROTOBUF_NODISCARD ::common::Error* release_error();
  ::common::Error* mutable_error();
  void set_allocated_error(::common::Error* error);
  private:
  const ::common::Error& _internal_error() const;
  ::common::Error* _internal_mutable_error();
  public:
  void unsafe_arena_set_allocated_error(
      ::common::Error* error);
  ::common::Error* unsafe_arena_release_error();
  // .common.Status status = 1;
  void clear_status() ;
  ::common::Status status() const;
  void set_status(::common::Status value);

  private:
  ::common::Status _internal_status() const;
  void _internal_set_status(::common::Status value);

  public:
  // @@protoc_insertion_point(class_scope:agent.DTO.UpdateAvailableVersionsResult)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::common::Error* error_;
    int status_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_update_2davailable_2dversions_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// VersionMatrix

// .common.AgentVersion agent_version = 1;
inline bool VersionMatrix::_internal_has_agent_version() const {
  return this != internal_default_instance() && _impl_.agent_version_ != nullptr;
}
inline bool VersionMatrix::has_agent_version() const {
  return _internal_has_agent_version();
}
inline const ::common::AgentVersion& VersionMatrix::_internal_agent_version() const {
  const ::common::AgentVersion* p = _impl_.agent_version_;
  return p != nullptr ? *p : reinterpret_cast<const ::common::AgentVersion&>(
      ::common::_AgentVersion_default_instance_);
}
inline const ::common::AgentVersion& VersionMatrix::agent_version() const {
  // @@protoc_insertion_point(field_get:agent.DTO.VersionMatrix.agent_version)
  return _internal_agent_version();
}
inline void VersionMatrix::unsafe_arena_set_allocated_agent_version(
    ::common::AgentVersion* agent_version) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.agent_version_);
  }
  _impl_.agent_version_ = agent_version;
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:agent.DTO.VersionMatrix.agent_version)
}
inline ::common::AgentVersion* VersionMatrix::release_agent_version() {
  
  ::common::AgentVersion* temp = _impl_.agent_version_;
  _impl_.agent_version_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::common::AgentVersion* VersionMatrix::unsafe_arena_release_agent_version() {
  // @@protoc_insertion_point(field_release:agent.DTO.VersionMatrix.agent_version)
  
  ::common::AgentVersion* temp = _impl_.agent_version_;
  _impl_.agent_version_ = nullptr;
  return temp;
}
inline ::common::AgentVersion* VersionMatrix::_internal_mutable_agent_version() {
  
  if (_impl_.agent_version_ == nullptr) {
    auto* p = CreateMaybeMessage<::common::AgentVersion>(GetArenaForAllocation());
    _impl_.agent_version_ = p;
  }
  return _impl_.agent_version_;
}
inline ::common::AgentVersion* VersionMatrix::mutable_agent_version() {
  ::common::AgentVersion* _msg = _internal_mutable_agent_version();
  // @@protoc_insertion_point(field_mutable:agent.DTO.VersionMatrix.agent_version)
  return _msg;
}
inline void VersionMatrix::set_allocated_agent_version(::common::AgentVersion* agent_version) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.agent_version_);
  }
  if (agent_version) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(agent_version));
    if (message_arena != submessage_arena) {
      agent_version = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, agent_version, submessage_arena);
    }

  } else {

  }
  _impl_.agent_version_ = agent_version;
  // @@protoc_insertion_point(field_set_allocated:agent.DTO.VersionMatrix.agent_version)
}

// repeated .common.ServiceVersion service_version = 2;
inline int VersionMatrix::_internal_service_version_size() const {
  return _impl_.service_version_.size();
}
inline int VersionMatrix::service_version_size() const {
  return _internal_service_version_size();
}
inline ::common::ServiceVersion* VersionMatrix::mutable_service_version(int index) {
  // @@protoc_insertion_point(field_mutable:agent.DTO.VersionMatrix.service_version)
  return _impl_.service_version_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::common::ServiceVersion >*
VersionMatrix::mutable_service_version() {
  // @@protoc_insertion_point(field_mutable_list:agent.DTO.VersionMatrix.service_version)
  return &_impl_.service_version_;
}
inline const ::common::ServiceVersion& VersionMatrix::_internal_service_version(int index) const {
  return _impl_.service_version_.Get(index);
}
inline const ::common::ServiceVersion& VersionMatrix::service_version(int index) const {
  // @@protoc_insertion_point(field_get:agent.DTO.VersionMatrix.service_version)
  return _internal_service_version(index);
}
inline ::common::ServiceVersion* VersionMatrix::_internal_add_service_version() {
  return _impl_.service_version_.Add();
}
inline ::common::ServiceVersion* VersionMatrix::add_service_version() {
  ::common::ServiceVersion* _add = _internal_add_service_version();
  // @@protoc_insertion_point(field_add:agent.DTO.VersionMatrix.service_version)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::common::ServiceVersion >&
VersionMatrix::service_version() const {
  // @@protoc_insertion_point(field_list:agent.DTO.VersionMatrix.service_version)
  return _impl_.service_version_;
}

// -------------------------------------------------------------------

// UpdateAvailableVersionsInfo

// .common.UUID update_available_versions_request_id = 1;
inline bool UpdateAvailableVersionsInfo::_internal_has_update_available_versions_request_id() const {
  return this != internal_default_instance() && _impl_.update_available_versions_request_id_ != nullptr;
}
inline bool UpdateAvailableVersionsInfo::has_update_available_versions_request_id() const {
  return _internal_has_update_available_versions_request_id();
}
inline const ::common::UUID& UpdateAvailableVersionsInfo::_internal_update_available_versions_request_id() const {
  const ::common::UUID* p = _impl_.update_available_versions_request_id_;
  return p != nullptr ? *p : reinterpret_cast<const ::common::UUID&>(
      ::common::_UUID_default_instance_);
}
inline const ::common::UUID& UpdateAvailableVersionsInfo::update_available_versions_request_id() const {
  // @@protoc_insertion_point(field_get:agent.DTO.UpdateAvailableVersionsInfo.update_available_versions_request_id)
  return _internal_update_available_versions_request_id();
}
inline void UpdateAvailableVersionsInfo::unsafe_arena_set_allocated_update_available_versions_request_id(
    ::common::UUID* update_available_versions_request_id) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.update_available_versions_request_id_);
  }
  _impl_.update_available_versions_request_id_ = update_available_versions_request_id;
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:agent.DTO.UpdateAvailableVersionsInfo.update_available_versions_request_id)
}
inline ::common::UUID* UpdateAvailableVersionsInfo::release_update_available_versions_request_id() {
  
  ::common::UUID* temp = _impl_.update_available_versions_request_id_;
  _impl_.update_available_versions_request_id_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::common::UUID* UpdateAvailableVersionsInfo::unsafe_arena_release_update_available_versions_request_id() {
  // @@protoc_insertion_point(field_release:agent.DTO.UpdateAvailableVersionsInfo.update_available_versions_request_id)
  
  ::common::UUID* temp = _impl_.update_available_versions_request_id_;
  _impl_.update_available_versions_request_id_ = nullptr;
  return temp;
}
inline ::common::UUID* UpdateAvailableVersionsInfo::_internal_mutable_update_available_versions_request_id() {
  
  if (_impl_.update_available_versions_request_id_ == nullptr) {
    auto* p = CreateMaybeMessage<::common::UUID>(GetArenaForAllocation());
    _impl_.update_available_versions_request_id_ = p;
  }
  return _impl_.update_available_versions_request_id_;
}
inline ::common::UUID* UpdateAvailableVersionsInfo::mutable_update_available_versions_request_id() {
  ::common::UUID* _msg = _internal_mutable_update_available_versions_request_id();
  // @@protoc_insertion_point(field_mutable:agent.DTO.UpdateAvailableVersionsInfo.update_available_versions_request_id)
  return _msg;
}
inline void UpdateAvailableVersionsInfo::set_allocated_update_available_versions_request_id(::common::UUID* update_available_versions_request_id) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.update_available_versions_request_id_);
  }
  if (update_available_versions_request_id) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(update_available_versions_request_id));
    if (message_arena != submessage_arena) {
      update_available_versions_request_id = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, update_available_versions_request_id, submessage_arena);
    }

  } else {

  }
  _impl_.update_available_versions_request_id_ = update_available_versions_request_id;
  // @@protoc_insertion_point(field_set_allocated:agent.DTO.UpdateAvailableVersionsInfo.update_available_versions_request_id)
}

// .common.UUID agent_id = 2;
inline bool UpdateAvailableVersionsInfo::_internal_has_agent_id() const {
  return this != internal_default_instance() && _impl_.agent_id_ != nullptr;
}
inline bool UpdateAvailableVersionsInfo::has_agent_id() const {
  return _internal_has_agent_id();
}
inline const ::common::UUID& UpdateAvailableVersionsInfo::_internal_agent_id() const {
  const ::common::UUID* p = _impl_.agent_id_;
  return p != nullptr ? *p : reinterpret_cast<const ::common::UUID&>(
      ::common::_UUID_default_instance_);
}
inline const ::common::UUID& UpdateAvailableVersionsInfo::agent_id() const {
  // @@protoc_insertion_point(field_get:agent.DTO.UpdateAvailableVersionsInfo.agent_id)
  return _internal_agent_id();
}
inline void UpdateAvailableVersionsInfo::unsafe_arena_set_allocated_agent_id(
    ::common::UUID* agent_id) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.agent_id_);
  }
  _impl_.agent_id_ = agent_id;
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:agent.DTO.UpdateAvailableVersionsInfo.agent_id)
}
inline ::common::UUID* UpdateAvailableVersionsInfo::release_agent_id() {
  
  ::common::UUID* temp = _impl_.agent_id_;
  _impl_.agent_id_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::common::UUID* UpdateAvailableVersionsInfo::unsafe_arena_release_agent_id() {
  // @@protoc_insertion_point(field_release:agent.DTO.UpdateAvailableVersionsInfo.agent_id)
  
  ::common::UUID* temp = _impl_.agent_id_;
  _impl_.agent_id_ = nullptr;
  return temp;
}
inline ::common::UUID* UpdateAvailableVersionsInfo::_internal_mutable_agent_id() {
  
  if (_impl_.agent_id_ == nullptr) {
    auto* p = CreateMaybeMessage<::common::UUID>(GetArenaForAllocation());
    _impl_.agent_id_ = p;
  }
  return _impl_.agent_id_;
}
inline ::common::UUID* UpdateAvailableVersionsInfo::mutable_agent_id() {
  ::common::UUID* _msg = _internal_mutable_agent_id();
  // @@protoc_insertion_point(field_mutable:agent.DTO.UpdateAvailableVersionsInfo.agent_id)
  return _msg;
}
inline void UpdateAvailableVersionsInfo::set_allocated_agent_id(::common::UUID* agent_id) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.agent_id_);
  }
  if (agent_id) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(agent_id));
    if (message_arena != submessage_arena) {
      agent_id = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, agent_id, submessage_arena);
    }

  } else {

  }
  _impl_.agent_id_ = agent_id;
  // @@protoc_insertion_point(field_set_allocated:agent.DTO.UpdateAvailableVersionsInfo.agent_id)
}

// .common.AgentVersion current_agent_version = 3;
inline bool UpdateAvailableVersionsInfo::_internal_has_current_agent_version() const {
  return this != internal_default_instance() && _impl_.current_agent_version_ != nullptr;
}
inline bool UpdateAvailableVersionsInfo::has_current_agent_version() const {
  return _internal_has_current_agent_version();
}
inline const ::common::AgentVersion& UpdateAvailableVersionsInfo::_internal_current_agent_version() const {
  const ::common::AgentVersion* p = _impl_.current_agent_version_;
  return p != nullptr ? *p : reinterpret_cast<const ::common::AgentVersion&>(
      ::common::_AgentVersion_default_instance_);
}
inline const ::common::AgentVersion& UpdateAvailableVersionsInfo::current_agent_version() const {
  // @@protoc_insertion_point(field_get:agent.DTO.UpdateAvailableVersionsInfo.current_agent_version)
  return _internal_current_agent_version();
}
inline void UpdateAvailableVersionsInfo::unsafe_arena_set_allocated_current_agent_version(
    ::common::AgentVersion* current_agent_version) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.current_agent_version_);
  }
  _impl_.current_agent_version_ = current_agent_version;
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:agent.DTO.UpdateAvailableVersionsInfo.current_agent_version)
}
inline ::common::AgentVersion* UpdateAvailableVersionsInfo::release_current_agent_version() {
  
  ::common::AgentVersion* temp = _impl_.current_agent_version_;
  _impl_.current_agent_version_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::common::AgentVersion* UpdateAvailableVersionsInfo::unsafe_arena_release_current_agent_version() {
  // @@protoc_insertion_point(field_release:agent.DTO.UpdateAvailableVersionsInfo.current_agent_version)
  
  ::common::AgentVersion* temp = _impl_.current_agent_version_;
  _impl_.current_agent_version_ = nullptr;
  return temp;
}
inline ::common::AgentVersion* UpdateAvailableVersionsInfo::_internal_mutable_current_agent_version() {
  
  if (_impl_.current_agent_version_ == nullptr) {
    auto* p = CreateMaybeMessage<::common::AgentVersion>(GetArenaForAllocation());
    _impl_.current_agent_version_ = p;
  }
  return _impl_.current_agent_version_;
}
inline ::common::AgentVersion* UpdateAvailableVersionsInfo::mutable_current_agent_version() {
  ::common::AgentVersion* _msg = _internal_mutable_current_agent_version();
  // @@protoc_insertion_point(field_mutable:agent.DTO.UpdateAvailableVersionsInfo.current_agent_version)
  return _msg;
}
inline void UpdateAvailableVersionsInfo::set_allocated_current_agent_version(::common::AgentVersion* current_agent_version) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.current_agent_version_);
  }
  if (current_agent_version) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(current_agent_version));
    if (message_arena != submessage_arena) {
      current_agent_version = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, current_agent_version, submessage_arena);
    }

  } else {

  }
  _impl_.current_agent_version_ = current_agent_version;
  // @@protoc_insertion_point(field_set_allocated:agent.DTO.UpdateAvailableVersionsInfo.current_agent_version)
}

// .common.ServiceVersion current_service_version = 4;
inline bool UpdateAvailableVersionsInfo::_internal_has_current_service_version() const {
  return this != internal_default_instance() && _impl_.current_service_version_ != nullptr;
}
inline bool UpdateAvailableVersionsInfo::has_current_service_version() const {
  return _internal_has_current_service_version();
}
inline const ::common::ServiceVersion& UpdateAvailableVersionsInfo::_internal_current_service_version() const {
  const ::common::ServiceVersion* p = _impl_.current_service_version_;
  return p != nullptr ? *p : reinterpret_cast<const ::common::ServiceVersion&>(
      ::common::_ServiceVersion_default_instance_);
}
inline const ::common::ServiceVersion& UpdateAvailableVersionsInfo::current_service_version() const {
  // @@protoc_insertion_point(field_get:agent.DTO.UpdateAvailableVersionsInfo.current_service_version)
  return _internal_current_service_version();
}
inline void UpdateAvailableVersionsInfo::unsafe_arena_set_allocated_current_service_version(
    ::common::ServiceVersion* current_service_version) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.current_service_version_);
  }
  _impl_.current_service_version_ = current_service_version;
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:agent.DTO.UpdateAvailableVersionsInfo.current_service_version)
}
inline ::common::ServiceVersion* UpdateAvailableVersionsInfo::release_current_service_version() {
  
  ::common::ServiceVersion* temp = _impl_.current_service_version_;
  _impl_.current_service_version_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::common::ServiceVersion* UpdateAvailableVersionsInfo::unsafe_arena_release_current_service_version() {
  // @@protoc_insertion_point(field_release:agent.DTO.UpdateAvailableVersionsInfo.current_service_version)
  
  ::common::ServiceVersion* temp = _impl_.current_service_version_;
  _impl_.current_service_version_ = nullptr;
  return temp;
}
inline ::common::ServiceVersion* UpdateAvailableVersionsInfo::_internal_mutable_current_service_version() {
  
  if (_impl_.current_service_version_ == nullptr) {
    auto* p = CreateMaybeMessage<::common::ServiceVersion>(GetArenaForAllocation());
    _impl_.current_service_version_ = p;
  }
  return _impl_.current_service_version_;
}
inline ::common::ServiceVersion* UpdateAvailableVersionsInfo::mutable_current_service_version() {
  ::common::ServiceVersion* _msg = _internal_mutable_current_service_version();
  // @@protoc_insertion_point(field_mutable:agent.DTO.UpdateAvailableVersionsInfo.current_service_version)
  return _msg;
}
inline void UpdateAvailableVersionsInfo::set_allocated_current_service_version(::common::ServiceVersion* current_service_version) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.current_service_version_);
  }
  if (current_service_version) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(current_service_version));
    if (message_arena != submessage_arena) {
      current_service_version = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, current_service_version, submessage_arena);
    }

  } else {

  }
  _impl_.current_service_version_ = current_service_version;
  // @@protoc_insertion_point(field_set_allocated:agent.DTO.UpdateAvailableVersionsInfo.current_service_version)
}

// repeated .agent.DTO.VersionMatrix upgradable_versions = 5;
inline int UpdateAvailableVersionsInfo::_internal_upgradable_versions_size() const {
  return _impl_.upgradable_versions_.size();
}
inline int UpdateAvailableVersionsInfo::upgradable_versions_size() const {
  return _internal_upgradable_versions_size();
}
inline void UpdateAvailableVersionsInfo::clear_upgradable_versions() {
  _impl_.upgradable_versions_.Clear();
}
inline ::agent::DTO::VersionMatrix* UpdateAvailableVersionsInfo::mutable_upgradable_versions(int index) {
  // @@protoc_insertion_point(field_mutable:agent.DTO.UpdateAvailableVersionsInfo.upgradable_versions)
  return _impl_.upgradable_versions_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::agent::DTO::VersionMatrix >*
UpdateAvailableVersionsInfo::mutable_upgradable_versions() {
  // @@protoc_insertion_point(field_mutable_list:agent.DTO.UpdateAvailableVersionsInfo.upgradable_versions)
  return &_impl_.upgradable_versions_;
}
inline const ::agent::DTO::VersionMatrix& UpdateAvailableVersionsInfo::_internal_upgradable_versions(int index) const {
  return _impl_.upgradable_versions_.Get(index);
}
inline const ::agent::DTO::VersionMatrix& UpdateAvailableVersionsInfo::upgradable_versions(int index) const {
  // @@protoc_insertion_point(field_get:agent.DTO.UpdateAvailableVersionsInfo.upgradable_versions)
  return _internal_upgradable_versions(index);
}
inline ::agent::DTO::VersionMatrix* UpdateAvailableVersionsInfo::_internal_add_upgradable_versions() {
  return _impl_.upgradable_versions_.Add();
}
inline ::agent::DTO::VersionMatrix* UpdateAvailableVersionsInfo::add_upgradable_versions() {
  ::agent::DTO::VersionMatrix* _add = _internal_add_upgradable_versions();
  // @@protoc_insertion_point(field_add:agent.DTO.UpdateAvailableVersionsInfo.upgradable_versions)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::agent::DTO::VersionMatrix >&
UpdateAvailableVersionsInfo::upgradable_versions() const {
  // @@protoc_insertion_point(field_list:agent.DTO.UpdateAvailableVersionsInfo.upgradable_versions)
  return _impl_.upgradable_versions_;
}

// -------------------------------------------------------------------

// UpdateAvailableVersionsResult

// .common.Status status = 1;
inline void UpdateAvailableVersionsResult::clear_status() {
  _impl_.status_ = 0;
}
inline ::common::Status UpdateAvailableVersionsResult::status() const {
  // @@protoc_insertion_point(field_get:agent.DTO.UpdateAvailableVersionsResult.status)
  return _internal_status();
}
inline void UpdateAvailableVersionsResult::set_status(::common::Status value) {
   _internal_set_status(value);
  // @@protoc_insertion_point(field_set:agent.DTO.UpdateAvailableVersionsResult.status)
}
inline ::common::Status UpdateAvailableVersionsResult::_internal_status() const {
  return static_cast<::common::Status>(_impl_.status_);
}
inline void UpdateAvailableVersionsResult::_internal_set_status(::common::Status value) {
  ;
  _impl_.status_ = value;
}

// .common.Error error = 2;
inline bool UpdateAvailableVersionsResult::_internal_has_error() const {
  return this != internal_default_instance() && _impl_.error_ != nullptr;
}
inline bool UpdateAvailableVersionsResult::has_error() const {
  return _internal_has_error();
}
inline const ::common::Error& UpdateAvailableVersionsResult::_internal_error() const {
  const ::common::Error* p = _impl_.error_;
  return p != nullptr ? *p : reinterpret_cast<const ::common::Error&>(
      ::common::_Error_default_instance_);
}
inline const ::common::Error& UpdateAvailableVersionsResult::error() const {
  // @@protoc_insertion_point(field_get:agent.DTO.UpdateAvailableVersionsResult.error)
  return _internal_error();
}
inline void UpdateAvailableVersionsResult::unsafe_arena_set_allocated_error(
    ::common::Error* error) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.error_);
  }
  _impl_.error_ = error;
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:agent.DTO.UpdateAvailableVersionsResult.error)
}
inline ::common::Error* UpdateAvailableVersionsResult::release_error() {
  
  ::common::Error* temp = _impl_.error_;
  _impl_.error_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::common::Error* UpdateAvailableVersionsResult::unsafe_arena_release_error() {
  // @@protoc_insertion_point(field_release:agent.DTO.UpdateAvailableVersionsResult.error)
  
  ::common::Error* temp = _impl_.error_;
  _impl_.error_ = nullptr;
  return temp;
}
inline ::common::Error* UpdateAvailableVersionsResult::_internal_mutable_error() {
  
  if (_impl_.error_ == nullptr) {
    auto* p = CreateMaybeMessage<::common::Error>(GetArenaForAllocation());
    _impl_.error_ = p;
  }
  return _impl_.error_;
}
inline ::common::Error* UpdateAvailableVersionsResult::mutable_error() {
  ::common::Error* _msg = _internal_mutable_error();
  // @@protoc_insertion_point(field_mutable:agent.DTO.UpdateAvailableVersionsResult.error)
  return _msg;
}
inline void UpdateAvailableVersionsResult::set_allocated_error(::common::Error* error) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.error_);
  }
  if (error) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(error));
    if (message_arena != submessage_arena) {
      error = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, error, submessage_arena);
    }

  } else {

  }
  _impl_.error_ = error;
  // @@protoc_insertion_point(field_set_allocated:agent.DTO.UpdateAvailableVersionsResult.error)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace DTO
}  // namespace agent


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_update_2davailable_2dversions_2eproto_2epb_2eh
