// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: upgrade-service.proto

#include "upgrade-service.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace agent {
namespace DTO {
PROTOBUF_CONSTEXPR UpgradeServiceInfo::UpgradeServiceInfo(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.upgrade_service_request_id_)*/nullptr
  , /*decltype(_impl_.agent_id_)*/nullptr
  , /*decltype(_impl_.current_version_)*/nullptr
  , /*decltype(_impl_.to_version_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct UpgradeServiceInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UpgradeServiceInfoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UpgradeServiceInfoDefaultTypeInternal() {}
  union {
    UpgradeServiceInfo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UpgradeServiceInfoDefaultTypeInternal _UpgradeServiceInfo_default_instance_;
PROTOBUF_CONSTEXPR UpgradeServiceResult::UpgradeServiceResult(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.error_)*/nullptr
  , /*decltype(_impl_.status_)*/ 0

  , /*decltype(_impl_._cached_size_)*/{}} {}
struct UpgradeServiceResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UpgradeServiceResultDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UpgradeServiceResultDefaultTypeInternal() {}
  union {
    UpgradeServiceResult _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UpgradeServiceResultDefaultTypeInternal _UpgradeServiceResult_default_instance_;
}  // namespace DTO
}  // namespace agent
static ::_pb::Metadata file_level_metadata_upgrade_2dservice_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_upgrade_2dservice_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_upgrade_2dservice_2eproto = nullptr;
const ::uint32_t TableStruct_upgrade_2dservice_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::agent::DTO::UpgradeServiceInfo, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::agent::DTO::UpgradeServiceInfo, _impl_.upgrade_service_request_id_),
    PROTOBUF_FIELD_OFFSET(::agent::DTO::UpgradeServiceInfo, _impl_.agent_id_),
    PROTOBUF_FIELD_OFFSET(::agent::DTO::UpgradeServiceInfo, _impl_.current_version_),
    PROTOBUF_FIELD_OFFSET(::agent::DTO::UpgradeServiceInfo, _impl_.to_version_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::agent::DTO::UpgradeServiceResult, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::agent::DTO::UpgradeServiceResult, _impl_.status_),
    PROTOBUF_FIELD_OFFSET(::agent::DTO::UpgradeServiceResult, _impl_.error_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, -1, -1, sizeof(::agent::DTO::UpgradeServiceInfo)},
        { 12, -1, -1, sizeof(::agent::DTO::UpgradeServiceResult)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::agent::DTO::_UpgradeServiceInfo_default_instance_._instance,
    &::agent::DTO::_UpgradeServiceResult_default_instance_._instance,
};
const char descriptor_table_protodef_upgrade_2dservice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\025upgrade-service.proto\022\tagent.DTO\032\014comm"
    "on.proto\"\303\001\n\022UpgradeServiceInfo\0220\n\032upgra"
    "de_service_request_id\030\001 \001(\0132\014.common.UUI"
    "D\022\036\n\010agent_id\030\002 \001(\0132\014.common.UUID\022/\n\017cur"
    "rent_version\030\003 \001(\0132\026.common.ServiceVersi"
    "on\022*\n\nto_version\030\004 \001(\0132\026.common.ServiceV"
    "ersion\"T\n\024UpgradeServiceResult\022\036\n\006status"
    "\030\001 \001(\0162\016.common.Status\022\034\n\005error\030\002 \001(\0132\r."
    "common.Errorb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_upgrade_2dservice_2eproto_deps[1] =
    {
        &::descriptor_table_common_2eproto,
};
static ::absl::once_flag descriptor_table_upgrade_2dservice_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_upgrade_2dservice_2eproto = {
    false,
    false,
    340,
    descriptor_table_protodef_upgrade_2dservice_2eproto,
    "upgrade-service.proto",
    &descriptor_table_upgrade_2dservice_2eproto_once,
    descriptor_table_upgrade_2dservice_2eproto_deps,
    1,
    2,
    schemas,
    file_default_instances,
    TableStruct_upgrade_2dservice_2eproto::offsets,
    file_level_metadata_upgrade_2dservice_2eproto,
    file_level_enum_descriptors_upgrade_2dservice_2eproto,
    file_level_service_descriptors_upgrade_2dservice_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_upgrade_2dservice_2eproto_getter() {
  return &descriptor_table_upgrade_2dservice_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_upgrade_2dservice_2eproto(&descriptor_table_upgrade_2dservice_2eproto);
namespace agent {
namespace DTO {
// ===================================================================

class UpgradeServiceInfo::_Internal {
 public:
  static const ::common::UUID& upgrade_service_request_id(const UpgradeServiceInfo* msg);
  static const ::common::UUID& agent_id(const UpgradeServiceInfo* msg);
  static const ::common::ServiceVersion& current_version(const UpgradeServiceInfo* msg);
  static const ::common::ServiceVersion& to_version(const UpgradeServiceInfo* msg);
};

const ::common::UUID&
UpgradeServiceInfo::_Internal::upgrade_service_request_id(const UpgradeServiceInfo* msg) {
  return *msg->_impl_.upgrade_service_request_id_;
}
const ::common::UUID&
UpgradeServiceInfo::_Internal::agent_id(const UpgradeServiceInfo* msg) {
  return *msg->_impl_.agent_id_;
}
const ::common::ServiceVersion&
UpgradeServiceInfo::_Internal::current_version(const UpgradeServiceInfo* msg) {
  return *msg->_impl_.current_version_;
}
const ::common::ServiceVersion&
UpgradeServiceInfo::_Internal::to_version(const UpgradeServiceInfo* msg) {
  return *msg->_impl_.to_version_;
}
void UpgradeServiceInfo::clear_upgrade_service_request_id() {
  if (GetArenaForAllocation() == nullptr && _impl_.upgrade_service_request_id_ != nullptr) {
    delete _impl_.upgrade_service_request_id_;
  }
  _impl_.upgrade_service_request_id_ = nullptr;
}
void UpgradeServiceInfo::clear_agent_id() {
  if (GetArenaForAllocation() == nullptr && _impl_.agent_id_ != nullptr) {
    delete _impl_.agent_id_;
  }
  _impl_.agent_id_ = nullptr;
}
void UpgradeServiceInfo::clear_current_version() {
  if (GetArenaForAllocation() == nullptr && _impl_.current_version_ != nullptr) {
    delete _impl_.current_version_;
  }
  _impl_.current_version_ = nullptr;
}
void UpgradeServiceInfo::clear_to_version() {
  if (GetArenaForAllocation() == nullptr && _impl_.to_version_ != nullptr) {
    delete _impl_.to_version_;
  }
  _impl_.to_version_ = nullptr;
}
UpgradeServiceInfo::UpgradeServiceInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:agent.DTO.UpgradeServiceInfo)
}
UpgradeServiceInfo::UpgradeServiceInfo(const UpgradeServiceInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  UpgradeServiceInfo* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.upgrade_service_request_id_){nullptr}
    , decltype(_impl_.agent_id_){nullptr}
    , decltype(_impl_.current_version_){nullptr}
    , decltype(_impl_.to_version_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_upgrade_service_request_id()) {
    _this->_impl_.upgrade_service_request_id_ = new ::common::UUID(*from._impl_.upgrade_service_request_id_);
  }
  if (from._internal_has_agent_id()) {
    _this->_impl_.agent_id_ = new ::common::UUID(*from._impl_.agent_id_);
  }
  if (from._internal_has_current_version()) {
    _this->_impl_.current_version_ = new ::common::ServiceVersion(*from._impl_.current_version_);
  }
  if (from._internal_has_to_version()) {
    _this->_impl_.to_version_ = new ::common::ServiceVersion(*from._impl_.to_version_);
  }
  // @@protoc_insertion_point(copy_constructor:agent.DTO.UpgradeServiceInfo)
}

inline void UpgradeServiceInfo::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.upgrade_service_request_id_){nullptr}
    , decltype(_impl_.agent_id_){nullptr}
    , decltype(_impl_.current_version_){nullptr}
    , decltype(_impl_.to_version_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

UpgradeServiceInfo::~UpgradeServiceInfo() {
  // @@protoc_insertion_point(destructor:agent.DTO.UpgradeServiceInfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void UpgradeServiceInfo::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.upgrade_service_request_id_;
  if (this != internal_default_instance()) delete _impl_.agent_id_;
  if (this != internal_default_instance()) delete _impl_.current_version_;
  if (this != internal_default_instance()) delete _impl_.to_version_;
}

void UpgradeServiceInfo::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void UpgradeServiceInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:agent.DTO.UpgradeServiceInfo)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.upgrade_service_request_id_ != nullptr) {
    delete _impl_.upgrade_service_request_id_;
  }
  _impl_.upgrade_service_request_id_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.agent_id_ != nullptr) {
    delete _impl_.agent_id_;
  }
  _impl_.agent_id_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.current_version_ != nullptr) {
    delete _impl_.current_version_;
  }
  _impl_.current_version_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.to_version_ != nullptr) {
    delete _impl_.to_version_;
  }
  _impl_.to_version_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UpgradeServiceInfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .common.UUID upgrade_service_request_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_upgrade_service_request_id(), ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // .common.UUID agent_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_agent_id(), ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // .common.ServiceVersion current_version = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_current_version(), ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // .common.ServiceVersion to_version = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_to_version(), ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* UpgradeServiceInfo::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:agent.DTO.UpgradeServiceInfo)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .common.UUID upgrade_service_request_id = 1;
  if (this->_internal_has_upgrade_service_request_id()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::upgrade_service_request_id(this),
        _Internal::upgrade_service_request_id(this).GetCachedSize(), target, stream);
  }

  // .common.UUID agent_id = 2;
  if (this->_internal_has_agent_id()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::agent_id(this),
        _Internal::agent_id(this).GetCachedSize(), target, stream);
  }

  // .common.ServiceVersion current_version = 3;
  if (this->_internal_has_current_version()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::current_version(this),
        _Internal::current_version(this).GetCachedSize(), target, stream);
  }

  // .common.ServiceVersion to_version = 4;
  if (this->_internal_has_to_version()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::to_version(this),
        _Internal::to_version(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:agent.DTO.UpgradeServiceInfo)
  return target;
}

::size_t UpgradeServiceInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:agent.DTO.UpgradeServiceInfo)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .common.UUID upgrade_service_request_id = 1;
  if (this->_internal_has_upgrade_service_request_id()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.upgrade_service_request_id_);
  }

  // .common.UUID agent_id = 2;
  if (this->_internal_has_agent_id()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.agent_id_);
  }

  // .common.ServiceVersion current_version = 3;
  if (this->_internal_has_current_version()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.current_version_);
  }

  // .common.ServiceVersion to_version = 4;
  if (this->_internal_has_to_version()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.to_version_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData UpgradeServiceInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    UpgradeServiceInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*UpgradeServiceInfo::GetClassData() const { return &_class_data_; }


void UpgradeServiceInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<UpgradeServiceInfo*>(&to_msg);
  auto& from = static_cast<const UpgradeServiceInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:agent.DTO.UpgradeServiceInfo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_upgrade_service_request_id()) {
    _this->_internal_mutable_upgrade_service_request_id()->::common::UUID::MergeFrom(
        from._internal_upgrade_service_request_id());
  }
  if (from._internal_has_agent_id()) {
    _this->_internal_mutable_agent_id()->::common::UUID::MergeFrom(
        from._internal_agent_id());
  }
  if (from._internal_has_current_version()) {
    _this->_internal_mutable_current_version()->::common::ServiceVersion::MergeFrom(
        from._internal_current_version());
  }
  if (from._internal_has_to_version()) {
    _this->_internal_mutable_to_version()->::common::ServiceVersion::MergeFrom(
        from._internal_to_version());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void UpgradeServiceInfo::CopyFrom(const UpgradeServiceInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:agent.DTO.UpgradeServiceInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UpgradeServiceInfo::IsInitialized() const {
  return true;
}

void UpgradeServiceInfo::InternalSwap(UpgradeServiceInfo* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UpgradeServiceInfo, _impl_.to_version_)
      + sizeof(UpgradeServiceInfo::_impl_.to_version_)
      - PROTOBUF_FIELD_OFFSET(UpgradeServiceInfo, _impl_.upgrade_service_request_id_)>(
          reinterpret_cast<char*>(&_impl_.upgrade_service_request_id_),
          reinterpret_cast<char*>(&other->_impl_.upgrade_service_request_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata UpgradeServiceInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_upgrade_2dservice_2eproto_getter, &descriptor_table_upgrade_2dservice_2eproto_once,
      file_level_metadata_upgrade_2dservice_2eproto[0]);
}
// ===================================================================

class UpgradeServiceResult::_Internal {
 public:
  static const ::common::Error& error(const UpgradeServiceResult* msg);
};

const ::common::Error&
UpgradeServiceResult::_Internal::error(const UpgradeServiceResult* msg) {
  return *msg->_impl_.error_;
}
void UpgradeServiceResult::clear_error() {
  if (GetArenaForAllocation() == nullptr && _impl_.error_ != nullptr) {
    delete _impl_.error_;
  }
  _impl_.error_ = nullptr;
}
UpgradeServiceResult::UpgradeServiceResult(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:agent.DTO.UpgradeServiceResult)
}
UpgradeServiceResult::UpgradeServiceResult(const UpgradeServiceResult& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  UpgradeServiceResult* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.error_){nullptr}
    , decltype(_impl_.status_) {}

    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_error()) {
    _this->_impl_.error_ = new ::common::Error(*from._impl_.error_);
  }
  _this->_impl_.status_ = from._impl_.status_;
  // @@protoc_insertion_point(copy_constructor:agent.DTO.UpgradeServiceResult)
}

inline void UpgradeServiceResult::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.error_){nullptr}
    , decltype(_impl_.status_) { 0 }

    , /*decltype(_impl_._cached_size_)*/{}
  };
}

UpgradeServiceResult::~UpgradeServiceResult() {
  // @@protoc_insertion_point(destructor:agent.DTO.UpgradeServiceResult)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void UpgradeServiceResult::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.error_;
}

void UpgradeServiceResult::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void UpgradeServiceResult::Clear() {
// @@protoc_insertion_point(message_clear_start:agent.DTO.UpgradeServiceResult)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.error_ != nullptr) {
    delete _impl_.error_;
  }
  _impl_.error_ = nullptr;
  _impl_.status_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UpgradeServiceResult::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .common.Status status = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 8)) {
          ::uint32_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
          _internal_set_status(static_cast<::common::Status>(val));
        } else {
          goto handle_unusual;
        }
        continue;
      // .common.Error error = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_error(), ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* UpgradeServiceResult::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:agent.DTO.UpgradeServiceResult)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .common.Status status = 1;
  if (this->_internal_status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_status(), target);
  }

  // .common.Error error = 2;
  if (this->_internal_has_error()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::error(this),
        _Internal::error(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:agent.DTO.UpgradeServiceResult)
  return target;
}

::size_t UpgradeServiceResult::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:agent.DTO.UpgradeServiceResult)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .common.Error error = 2;
  if (this->_internal_has_error()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.error_);
  }

  // .common.Status status = 1;
  if (this->_internal_status() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_status());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData UpgradeServiceResult::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    UpgradeServiceResult::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*UpgradeServiceResult::GetClassData() const { return &_class_data_; }


void UpgradeServiceResult::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<UpgradeServiceResult*>(&to_msg);
  auto& from = static_cast<const UpgradeServiceResult&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:agent.DTO.UpgradeServiceResult)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_error()) {
    _this->_internal_mutable_error()->::common::Error::MergeFrom(
        from._internal_error());
  }
  if (from._internal_status() != 0) {
    _this->_internal_set_status(from._internal_status());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void UpgradeServiceResult::CopyFrom(const UpgradeServiceResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:agent.DTO.UpgradeServiceResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UpgradeServiceResult::IsInitialized() const {
  return true;
}

void UpgradeServiceResult::InternalSwap(UpgradeServiceResult* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UpgradeServiceResult, _impl_.status_)
      + sizeof(UpgradeServiceResult::_impl_.status_)
      - PROTOBUF_FIELD_OFFSET(UpgradeServiceResult, _impl_.error_)>(
          reinterpret_cast<char*>(&_impl_.error_),
          reinterpret_cast<char*>(&other->_impl_.error_));
}

::PROTOBUF_NAMESPACE_ID::Metadata UpgradeServiceResult::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_upgrade_2dservice_2eproto_getter, &descriptor_table_upgrade_2dservice_2eproto_once,
      file_level_metadata_upgrade_2dservice_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace DTO
}  // namespace agent
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::agent::DTO::UpgradeServiceInfo*
Arena::CreateMaybeMessage< ::agent::DTO::UpgradeServiceInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::agent::DTO::UpgradeServiceInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::agent::DTO::UpgradeServiceResult*
Arena::CreateMaybeMessage< ::agent::DTO::UpgradeServiceResult >(Arena* arena) {
  return Arena::CreateMessageInternal< ::agent::DTO::UpgradeServiceResult >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
