// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: upgrade-agent.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_upgrade_2dagent_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_upgrade_2dagent_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4022000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4022001 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "common.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_upgrade_2dagent_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_upgrade_2dagent_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_upgrade_2dagent_2eproto;
namespace agent {
namespace DTO {
class UpgradeAgentInfo;
struct UpgradeAgentInfoDefaultTypeInternal;
extern UpgradeAgentInfoDefaultTypeInternal _UpgradeAgentInfo_default_instance_;
class UpgradeAgentResult;
struct UpgradeAgentResultDefaultTypeInternal;
extern UpgradeAgentResultDefaultTypeInternal _UpgradeAgentResult_default_instance_;
}  // namespace DTO
}  // namespace agent
PROTOBUF_NAMESPACE_OPEN
template <>
::agent::DTO::UpgradeAgentInfo* Arena::CreateMaybeMessage<::agent::DTO::UpgradeAgentInfo>(Arena*);
template <>
::agent::DTO::UpgradeAgentResult* Arena::CreateMaybeMessage<::agent::DTO::UpgradeAgentResult>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace agent {
namespace DTO {

// ===================================================================


// -------------------------------------------------------------------

class UpgradeAgentInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:agent.DTO.UpgradeAgentInfo) */ {
 public:
  inline UpgradeAgentInfo() : UpgradeAgentInfo(nullptr) {}
  ~UpgradeAgentInfo() override;
  explicit PROTOBUF_CONSTEXPR UpgradeAgentInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UpgradeAgentInfo(const UpgradeAgentInfo& from);
  UpgradeAgentInfo(UpgradeAgentInfo&& from) noexcept
    : UpgradeAgentInfo() {
    *this = ::std::move(from);
  }

  inline UpgradeAgentInfo& operator=(const UpgradeAgentInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline UpgradeAgentInfo& operator=(UpgradeAgentInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UpgradeAgentInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const UpgradeAgentInfo* internal_default_instance() {
    return reinterpret_cast<const UpgradeAgentInfo*>(
               &_UpgradeAgentInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(UpgradeAgentInfo& a, UpgradeAgentInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(UpgradeAgentInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UpgradeAgentInfo* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UpgradeAgentInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UpgradeAgentInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UpgradeAgentInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const UpgradeAgentInfo& from) {
    UpgradeAgentInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UpgradeAgentInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "agent.DTO.UpgradeAgentInfo";
  }
  protected:
  explicit UpgradeAgentInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUpgradeAgentRequestIdFieldNumber = 1,
    kAgentIdFieldNumber = 2,
    kCurrentVersionFieldNumber = 3,
    kToVersionFieldNumber = 4,
  };
  // .common.UUID upgrade_agent_request_id = 1;
  bool has_upgrade_agent_request_id() const;
  private:
  bool _internal_has_upgrade_agent_request_id() const;

  public:
  void clear_upgrade_agent_request_id() ;
  const ::common::UUID& upgrade_agent_request_id() const;
  PROTOBUF_NODISCARD ::common::UUID* release_upgrade_agent_request_id();
  ::common::UUID* mutable_upgrade_agent_request_id();
  void set_allocated_upgrade_agent_request_id(::common::UUID* upgrade_agent_request_id);
  private:
  const ::common::UUID& _internal_upgrade_agent_request_id() const;
  ::common::UUID* _internal_mutable_upgrade_agent_request_id();
  public:
  void unsafe_arena_set_allocated_upgrade_agent_request_id(
      ::common::UUID* upgrade_agent_request_id);
  ::common::UUID* unsafe_arena_release_upgrade_agent_request_id();
  // .common.UUID agent_id = 2;
  bool has_agent_id() const;
  private:
  bool _internal_has_agent_id() const;

  public:
  void clear_agent_id() ;
  const ::common::UUID& agent_id() const;
  PROTOBUF_NODISCARD ::common::UUID* release_agent_id();
  ::common::UUID* mutable_agent_id();
  void set_allocated_agent_id(::common::UUID* agent_id);
  private:
  const ::common::UUID& _internal_agent_id() const;
  ::common::UUID* _internal_mutable_agent_id();
  public:
  void unsafe_arena_set_allocated_agent_id(
      ::common::UUID* agent_id);
  ::common::UUID* unsafe_arena_release_agent_id();
  // .common.AgentVersion current_version = 3;
  bool has_current_version() const;
  private:
  bool _internal_has_current_version() const;

  public:
  void clear_current_version() ;
  const ::common::AgentVersion& current_version() const;
  PROTOBUF_NODISCARD ::common::AgentVersion* release_current_version();
  ::common::AgentVersion* mutable_current_version();
  void set_allocated_current_version(::common::AgentVersion* current_version);
  private:
  const ::common::AgentVersion& _internal_current_version() const;
  ::common::AgentVersion* _internal_mutable_current_version();
  public:
  void unsafe_arena_set_allocated_current_version(
      ::common::AgentVersion* current_version);
  ::common::AgentVersion* unsafe_arena_release_current_version();
  // .common.AgentVersion to_version = 4;
  bool has_to_version() const;
  private:
  bool _internal_has_to_version() const;

  public:
  void clear_to_version() ;
  const ::common::AgentVersion& to_version() const;
  PROTOBUF_NODISCARD ::common::AgentVersion* release_to_version();
  ::common::AgentVersion* mutable_to_version();
  void set_allocated_to_version(::common::AgentVersion* to_version);
  private:
  const ::common::AgentVersion& _internal_to_version() const;
  ::common::AgentVersion* _internal_mutable_to_version();
  public:
  void unsafe_arena_set_allocated_to_version(
      ::common::AgentVersion* to_version);
  ::common::AgentVersion* unsafe_arena_release_to_version();
  // @@protoc_insertion_point(class_scope:agent.DTO.UpgradeAgentInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::common::UUID* upgrade_agent_request_id_;
    ::common::UUID* agent_id_;
    ::common::AgentVersion* current_version_;
    ::common::AgentVersion* to_version_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_upgrade_2dagent_2eproto;
};// -------------------------------------------------------------------

class UpgradeAgentResult final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:agent.DTO.UpgradeAgentResult) */ {
 public:
  inline UpgradeAgentResult() : UpgradeAgentResult(nullptr) {}
  ~UpgradeAgentResult() override;
  explicit PROTOBUF_CONSTEXPR UpgradeAgentResult(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UpgradeAgentResult(const UpgradeAgentResult& from);
  UpgradeAgentResult(UpgradeAgentResult&& from) noexcept
    : UpgradeAgentResult() {
    *this = ::std::move(from);
  }

  inline UpgradeAgentResult& operator=(const UpgradeAgentResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline UpgradeAgentResult& operator=(UpgradeAgentResult&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UpgradeAgentResult& default_instance() {
    return *internal_default_instance();
  }
  static inline const UpgradeAgentResult* internal_default_instance() {
    return reinterpret_cast<const UpgradeAgentResult*>(
               &_UpgradeAgentResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(UpgradeAgentResult& a, UpgradeAgentResult& b) {
    a.Swap(&b);
  }
  inline void Swap(UpgradeAgentResult* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UpgradeAgentResult* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UpgradeAgentResult* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UpgradeAgentResult>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UpgradeAgentResult& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const UpgradeAgentResult& from) {
    UpgradeAgentResult::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UpgradeAgentResult* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "agent.DTO.UpgradeAgentResult";
  }
  protected:
  explicit UpgradeAgentResult(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrorFieldNumber = 2,
    kStatusFieldNumber = 1,
  };
  // .common.Error error = 2;
  bool has_error() const;
  private:
  bool _internal_has_error() const;

  public:
  void clear_error() ;
  const ::common::Error& error() const;
  PROTOBUF_NODISCARD ::common::Error* release_error();
  ::common::Error* mutable_error();
  void set_allocated_error(::common::Error* error);
  private:
  const ::common::Error& _internal_error() const;
  ::common::Error* _internal_mutable_error();
  public:
  void unsafe_arena_set_allocated_error(
      ::common::Error* error);
  ::common::Error* unsafe_arena_release_error();
  // .common.Status status = 1;
  void clear_status() ;
  ::common::Status status() const;
  void set_status(::common::Status value);

  private:
  ::common::Status _internal_status() const;
  void _internal_set_status(::common::Status value);

  public:
  // @@protoc_insertion_point(class_scope:agent.DTO.UpgradeAgentResult)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::common::Error* error_;
    int status_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_upgrade_2dagent_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// UpgradeAgentInfo

// .common.UUID upgrade_agent_request_id = 1;
inline bool UpgradeAgentInfo::_internal_has_upgrade_agent_request_id() const {
  return this != internal_default_instance() && _impl_.upgrade_agent_request_id_ != nullptr;
}
inline bool UpgradeAgentInfo::has_upgrade_agent_request_id() const {
  return _internal_has_upgrade_agent_request_id();
}
inline const ::common::UUID& UpgradeAgentInfo::_internal_upgrade_agent_request_id() const {
  const ::common::UUID* p = _impl_.upgrade_agent_request_id_;
  return p != nullptr ? *p : reinterpret_cast<const ::common::UUID&>(
      ::common::_UUID_default_instance_);
}
inline const ::common::UUID& UpgradeAgentInfo::upgrade_agent_request_id() const {
  // @@protoc_insertion_point(field_get:agent.DTO.UpgradeAgentInfo.upgrade_agent_request_id)
  return _internal_upgrade_agent_request_id();
}
inline void UpgradeAgentInfo::unsafe_arena_set_allocated_upgrade_agent_request_id(
    ::common::UUID* upgrade_agent_request_id) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.upgrade_agent_request_id_);
  }
  _impl_.upgrade_agent_request_id_ = upgrade_agent_request_id;
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:agent.DTO.UpgradeAgentInfo.upgrade_agent_request_id)
}
inline ::common::UUID* UpgradeAgentInfo::release_upgrade_agent_request_id() {
  
  ::common::UUID* temp = _impl_.upgrade_agent_request_id_;
  _impl_.upgrade_agent_request_id_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::common::UUID* UpgradeAgentInfo::unsafe_arena_release_upgrade_agent_request_id() {
  // @@protoc_insertion_point(field_release:agent.DTO.UpgradeAgentInfo.upgrade_agent_request_id)
  
  ::common::UUID* temp = _impl_.upgrade_agent_request_id_;
  _impl_.upgrade_agent_request_id_ = nullptr;
  return temp;
}
inline ::common::UUID* UpgradeAgentInfo::_internal_mutable_upgrade_agent_request_id() {
  
  if (_impl_.upgrade_agent_request_id_ == nullptr) {
    auto* p = CreateMaybeMessage<::common::UUID>(GetArenaForAllocation());
    _impl_.upgrade_agent_request_id_ = p;
  }
  return _impl_.upgrade_agent_request_id_;
}
inline ::common::UUID* UpgradeAgentInfo::mutable_upgrade_agent_request_id() {
  ::common::UUID* _msg = _internal_mutable_upgrade_agent_request_id();
  // @@protoc_insertion_point(field_mutable:agent.DTO.UpgradeAgentInfo.upgrade_agent_request_id)
  return _msg;
}
inline void UpgradeAgentInfo::set_allocated_upgrade_agent_request_id(::common::UUID* upgrade_agent_request_id) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.upgrade_agent_request_id_);
  }
  if (upgrade_agent_request_id) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(upgrade_agent_request_id));
    if (message_arena != submessage_arena) {
      upgrade_agent_request_id = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, upgrade_agent_request_id, submessage_arena);
    }

  } else {

  }
  _impl_.upgrade_agent_request_id_ = upgrade_agent_request_id;
  // @@protoc_insertion_point(field_set_allocated:agent.DTO.UpgradeAgentInfo.upgrade_agent_request_id)
}

// .common.UUID agent_id = 2;
inline bool UpgradeAgentInfo::_internal_has_agent_id() const {
  return this != internal_default_instance() && _impl_.agent_id_ != nullptr;
}
inline bool UpgradeAgentInfo::has_agent_id() const {
  return _internal_has_agent_id();
}
inline const ::common::UUID& UpgradeAgentInfo::_internal_agent_id() const {
  const ::common::UUID* p = _impl_.agent_id_;
  return p != nullptr ? *p : reinterpret_cast<const ::common::UUID&>(
      ::common::_UUID_default_instance_);
}
inline const ::common::UUID& UpgradeAgentInfo::agent_id() const {
  // @@protoc_insertion_point(field_get:agent.DTO.UpgradeAgentInfo.agent_id)
  return _internal_agent_id();
}
inline void UpgradeAgentInfo::unsafe_arena_set_allocated_agent_id(
    ::common::UUID* agent_id) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.agent_id_);
  }
  _impl_.agent_id_ = agent_id;
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:agent.DTO.UpgradeAgentInfo.agent_id)
}
inline ::common::UUID* UpgradeAgentInfo::release_agent_id() {
  
  ::common::UUID* temp = _impl_.agent_id_;
  _impl_.agent_id_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::common::UUID* UpgradeAgentInfo::unsafe_arena_release_agent_id() {
  // @@protoc_insertion_point(field_release:agent.DTO.UpgradeAgentInfo.agent_id)
  
  ::common::UUID* temp = _impl_.agent_id_;
  _impl_.agent_id_ = nullptr;
  return temp;
}
inline ::common::UUID* UpgradeAgentInfo::_internal_mutable_agent_id() {
  
  if (_impl_.agent_id_ == nullptr) {
    auto* p = CreateMaybeMessage<::common::UUID>(GetArenaForAllocation());
    _impl_.agent_id_ = p;
  }
  return _impl_.agent_id_;
}
inline ::common::UUID* UpgradeAgentInfo::mutable_agent_id() {
  ::common::UUID* _msg = _internal_mutable_agent_id();
  // @@protoc_insertion_point(field_mutable:agent.DTO.UpgradeAgentInfo.agent_id)
  return _msg;
}
inline void UpgradeAgentInfo::set_allocated_agent_id(::common::UUID* agent_id) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.agent_id_);
  }
  if (agent_id) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(agent_id));
    if (message_arena != submessage_arena) {
      agent_id = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, agent_id, submessage_arena);
    }

  } else {

  }
  _impl_.agent_id_ = agent_id;
  // @@protoc_insertion_point(field_set_allocated:agent.DTO.UpgradeAgentInfo.agent_id)
}

// .common.AgentVersion current_version = 3;
inline bool UpgradeAgentInfo::_internal_has_current_version() const {
  return this != internal_default_instance() && _impl_.current_version_ != nullptr;
}
inline bool UpgradeAgentInfo::has_current_version() const {
  return _internal_has_current_version();
}
inline const ::common::AgentVersion& UpgradeAgentInfo::_internal_current_version() const {
  const ::common::AgentVersion* p = _impl_.current_version_;
  return p != nullptr ? *p : reinterpret_cast<const ::common::AgentVersion&>(
      ::common::_AgentVersion_default_instance_);
}
inline const ::common::AgentVersion& UpgradeAgentInfo::current_version() const {
  // @@protoc_insertion_point(field_get:agent.DTO.UpgradeAgentInfo.current_version)
  return _internal_current_version();
}
inline void UpgradeAgentInfo::unsafe_arena_set_allocated_current_version(
    ::common::AgentVersion* current_version) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.current_version_);
  }
  _impl_.current_version_ = current_version;
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:agent.DTO.UpgradeAgentInfo.current_version)
}
inline ::common::AgentVersion* UpgradeAgentInfo::release_current_version() {
  
  ::common::AgentVersion* temp = _impl_.current_version_;
  _impl_.current_version_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::common::AgentVersion* UpgradeAgentInfo::unsafe_arena_release_current_version() {
  // @@protoc_insertion_point(field_release:agent.DTO.UpgradeAgentInfo.current_version)
  
  ::common::AgentVersion* temp = _impl_.current_version_;
  _impl_.current_version_ = nullptr;
  return temp;
}
inline ::common::AgentVersion* UpgradeAgentInfo::_internal_mutable_current_version() {
  
  if (_impl_.current_version_ == nullptr) {
    auto* p = CreateMaybeMessage<::common::AgentVersion>(GetArenaForAllocation());
    _impl_.current_version_ = p;
  }
  return _impl_.current_version_;
}
inline ::common::AgentVersion* UpgradeAgentInfo::mutable_current_version() {
  ::common::AgentVersion* _msg = _internal_mutable_current_version();
  // @@protoc_insertion_point(field_mutable:agent.DTO.UpgradeAgentInfo.current_version)
  return _msg;
}
inline void UpgradeAgentInfo::set_allocated_current_version(::common::AgentVersion* current_version) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.current_version_);
  }
  if (current_version) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(current_version));
    if (message_arena != submessage_arena) {
      current_version = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, current_version, submessage_arena);
    }

  } else {

  }
  _impl_.current_version_ = current_version;
  // @@protoc_insertion_point(field_set_allocated:agent.DTO.UpgradeAgentInfo.current_version)
}

// .common.AgentVersion to_version = 4;
inline bool UpgradeAgentInfo::_internal_has_to_version() const {
  return this != internal_default_instance() && _impl_.to_version_ != nullptr;
}
inline bool UpgradeAgentInfo::has_to_version() const {
  return _internal_has_to_version();
}
inline const ::common::AgentVersion& UpgradeAgentInfo::_internal_to_version() const {
  const ::common::AgentVersion* p = _impl_.to_version_;
  return p != nullptr ? *p : reinterpret_cast<const ::common::AgentVersion&>(
      ::common::_AgentVersion_default_instance_);
}
inline const ::common::AgentVersion& UpgradeAgentInfo::to_version() const {
  // @@protoc_insertion_point(field_get:agent.DTO.UpgradeAgentInfo.to_version)
  return _internal_to_version();
}
inline void UpgradeAgentInfo::unsafe_arena_set_allocated_to_version(
    ::common::AgentVersion* to_version) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.to_version_);
  }
  _impl_.to_version_ = to_version;
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:agent.DTO.UpgradeAgentInfo.to_version)
}
inline ::common::AgentVersion* UpgradeAgentInfo::release_to_version() {
  
  ::common::AgentVersion* temp = _impl_.to_version_;
  _impl_.to_version_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::common::AgentVersion* UpgradeAgentInfo::unsafe_arena_release_to_version() {
  // @@protoc_insertion_point(field_release:agent.DTO.UpgradeAgentInfo.to_version)
  
  ::common::AgentVersion* temp = _impl_.to_version_;
  _impl_.to_version_ = nullptr;
  return temp;
}
inline ::common::AgentVersion* UpgradeAgentInfo::_internal_mutable_to_version() {
  
  if (_impl_.to_version_ == nullptr) {
    auto* p = CreateMaybeMessage<::common::AgentVersion>(GetArenaForAllocation());
    _impl_.to_version_ = p;
  }
  return _impl_.to_version_;
}
inline ::common::AgentVersion* UpgradeAgentInfo::mutable_to_version() {
  ::common::AgentVersion* _msg = _internal_mutable_to_version();
  // @@protoc_insertion_point(field_mutable:agent.DTO.UpgradeAgentInfo.to_version)
  return _msg;
}
inline void UpgradeAgentInfo::set_allocated_to_version(::common::AgentVersion* to_version) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.to_version_);
  }
  if (to_version) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(to_version));
    if (message_arena != submessage_arena) {
      to_version = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, to_version, submessage_arena);
    }

  } else {

  }
  _impl_.to_version_ = to_version;
  // @@protoc_insertion_point(field_set_allocated:agent.DTO.UpgradeAgentInfo.to_version)
}

// -------------------------------------------------------------------

// UpgradeAgentResult

// .common.Status status = 1;
inline void UpgradeAgentResult::clear_status() {
  _impl_.status_ = 0;
}
inline ::common::Status UpgradeAgentResult::status() const {
  // @@protoc_insertion_point(field_get:agent.DTO.UpgradeAgentResult.status)
  return _internal_status();
}
inline void UpgradeAgentResult::set_status(::common::Status value) {
   _internal_set_status(value);
  // @@protoc_insertion_point(field_set:agent.DTO.UpgradeAgentResult.status)
}
inline ::common::Status UpgradeAgentResult::_internal_status() const {
  return static_cast<::common::Status>(_impl_.status_);
}
inline void UpgradeAgentResult::_internal_set_status(::common::Status value) {
  ;
  _impl_.status_ = value;
}

// .common.Error error = 2;
inline bool UpgradeAgentResult::_internal_has_error() const {
  return this != internal_default_instance() && _impl_.error_ != nullptr;
}
inline bool UpgradeAgentResult::has_error() const {
  return _internal_has_error();
}
inline const ::common::Error& UpgradeAgentResult::_internal_error() const {
  const ::common::Error* p = _impl_.error_;
  return p != nullptr ? *p : reinterpret_cast<const ::common::Error&>(
      ::common::_Error_default_instance_);
}
inline const ::common::Error& UpgradeAgentResult::error() const {
  // @@protoc_insertion_point(field_get:agent.DTO.UpgradeAgentResult.error)
  return _internal_error();
}
inline void UpgradeAgentResult::unsafe_arena_set_allocated_error(
    ::common::Error* error) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.error_);
  }
  _impl_.error_ = error;
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:agent.DTO.UpgradeAgentResult.error)
}
inline ::common::Error* UpgradeAgentResult::release_error() {
  
  ::common::Error* temp = _impl_.error_;
  _impl_.error_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::common::Error* UpgradeAgentResult::unsafe_arena_release_error() {
  // @@protoc_insertion_point(field_release:agent.DTO.UpgradeAgentResult.error)
  
  ::common::Error* temp = _impl_.error_;
  _impl_.error_ = nullptr;
  return temp;
}
inline ::common::Error* UpgradeAgentResult::_internal_mutable_error() {
  
  if (_impl_.error_ == nullptr) {
    auto* p = CreateMaybeMessage<::common::Error>(GetArenaForAllocation());
    _impl_.error_ = p;
  }
  return _impl_.error_;
}
inline ::common::Error* UpgradeAgentResult::mutable_error() {
  ::common::Error* _msg = _internal_mutable_error();
  // @@protoc_insertion_point(field_mutable:agent.DTO.UpgradeAgentResult.error)
  return _msg;
}
inline void UpgradeAgentResult::set_allocated_error(::common::Error* error) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.error_);
  }
  if (error) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(error));
    if (message_arena != submessage_arena) {
      error = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, error, submessage_arena);
    }

  } else {

  }
  _impl_.error_ = error;
  // @@protoc_insertion_point(field_set_allocated:agent.DTO.UpgradeAgentResult.error)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace DTO
}  // namespace agent


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_upgrade_2dagent_2eproto_2epb_2eh
